import { Typography } from '@mui/material';
import Button from '@mui/material/Button';
import Head from 'next/head';
import HighlightedGradient from '../components/atoms/highlighted-gradient/HighlightedGradient';
import IllustrationMushroom1 from '../components/illustrations/illustration-mushroom-1';
import IllustrationMushroom2 from '../components/illustrations/illustration-mushroom-2';
import {
  Homepage,
  HomepageHeader, HomepageHeaderCtaDiscord, HomepageHeaderCtaJoin, HomepageHeaderCtaWrapper,
  HomepageHeaderInfo,
  HomepageHeaderSubtitle,
  HomepageIllustrationWrapper
} from '../styles';

// connect to contentful
// var client = contentful.createClient({
//   space: process.env.CONTENTFUL_SPACE_ID,
//   accessToken: process.env.CONTENTFUL_ACCESS_TOKEN,
// });

export default function Home(props) {
  console.log("props", props)
  return (
    <>
      <Head>
        <title>MYCELIUM.spctcl.io</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Homepage>
        <HomepageHeader>
          <HomepageHeaderInfo>
            <HighlightedGradient>
              <Typography variant="h1">MYCELIUM</Typography>
            </HighlightedGradient>
            <HomepageHeaderSubtitle>
              <Typography variant="body2">
                Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam
              </Typography>
            </HomepageHeaderSubtitle>
            <HomepageHeaderCtaWrapper>
              <HomepageHeaderCtaJoin>
                <Button variant="contained" size="large" sx={{
                  background: 'linear-gradient(90deg, rgba(5,3,72,1) 0%, rgba(112,9,121,1) 64%, rgba(152,244,246,1) 100%)',
                  borderRadius: '32px'
                }}>Join</Button>
              </HomepageHeaderCtaJoin>
              <HomepageHeaderCtaDiscord>
                <Button variant="contained" size="large">Discord</Button>
              </HomepageHeaderCtaDiscord>
            </HomepageHeaderCtaWrapper>
          </HomepageHeaderInfo>
          <HomepageIllustrationWrapper>
            <IllustrationMushroom1 />
            <IllustrationMushroom2 />
          </HomepageIllustrationWrapper>

        </HomepageHeader>
      </Homepage>
    </>)
}


export async function getStaticProps() {
  // get data from headless cms
  // const posts = await client.getEntries({
  //   content_type: "post"
  // })


  return {
    props: {
      // posts: await posts, // to pass posts fetched from contentful
    },
  }
}


